
INSERT INTO Areas (Name) VALUES
('INTELIGÊNCIA ARTIFICIAL'),
('ENGENHARIA DE SOFTWARE'),
('SISTEMAS DISTRIBUÍDOS'),
('REDES DE COMPUTADORES'),
('SEGURANÇA DA INFORMAÇÃO');

INSERT INTO Areas (Name) VALUES
('CIÊNCIA DE DADOS'),
('COMPUTAÇÃO GRÁFICA'),
('TEORIA DA COMPUTAÇÃO'),
('BANCO DE DADOS'),
('INTERAÇÃO HUMANO-COMPUTADOR');

INSERT INTO Areas (Name) VALUES
('PROGRAMÇÃO PARALELA E DISTRIBUÍDA'),
('ROBÓTICA'),
('PROCESSAMENTO DE IMAGENS'),
('MINERAÇÃO DE DADOS'),
('ENGENHARIA DE CONHECIMENTO');

INSERT INTO Areas (Name) VALUES
('PROGRAMAÇÃO WEB'),
('DESENVOLVIMENTO MOBILE'),
('TECNOLOGIAS DE FRONT-END'),
('BACK-END DEVELOPMENT'),
('ARQUITETURA DE SOFTWARE');

SELECT * FROM Areas