// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using connect_cic_api.Infra.Persistence;

#nullable disable

namespace connect_cic_api.Migrations
{
    [DbContext(typeof(ConnectCICAPIContext))]
    [Migration("20250527022113_AddAreasAndDisciplines")]
    partial class AddAreasAndDisciplines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("StudentVacancy", b =>
                {
                    b.Property<int>("StudentsStudentID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VacanciesVacancyID")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentsStudentID", "VacanciesVacancyID");

                    b.HasIndex("VacanciesVacancyID");

                    b.ToTable("StudentVacancy");
                });

            modelBuilder.Entity("connect_cic_api.Domain.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AreaId");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("connect_cic_api.Domain.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Objectives")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Syllabus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DisciplineId");

                    b.ToTable("Disciplines", (string)null);
                });

            modelBuilder.Entity("connect_cic_api.Domain.Professor", b =>
                {
                    b.Property<int>("ProfessorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfessorID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Professors", (string)null);

                    b.HasData(
                        new
                        {
                            ProfessorID = 1,
                            Department = "DCET",
                            Email = "professor.cic@uesc.br",
                            Name = "Professor Teste"
                        },
                        new
                        {
                            ProfessorID = 2,
                            Department = "DCET",
                            Email = "helder@uesc.com",
                            Name = "Helder"
                        },
                        new
                        {
                            ProfessorID = 3,
                            Department = "DCET",
                            Email = "martinha@uesc.com",
                            Name = "Martha"
                        },
                        new
                        {
                            ProfessorID = 4,
                            Department = "DCET",
                            Email = "bravo@uesc.com",
                            Name = "Bravo"
                        });
                });

            modelBuilder.Entity("connect_cic_api.Domain.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CRAA")
                        .HasColumnType("REAL");

                    b.Property<string>("Course")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            CRAA = 9f,
                            Course = "Ciencia da Computação",
                            Email = "aluno.cic@uesc.br",
                            Name = "Aluno teste",
                            Status = "Cursando"
                        },
                        new
                        {
                            StudentID = 2,
                            CRAA = 9f,
                            Course = "Ciencia da Computação",
                            Email = "everaldina@gmail.com",
                            Name = "Everaldina Barbosa",
                            Status = "Cursando"
                        },
                        new
                        {
                            StudentID = 3,
                            CRAA = 9f,
                            Course = "Ciencia da Computação",
                            Email = "lavinia@gmail.com",
                            Name = "Lavinia",
                            Status = "Cursando"
                        },
                        new
                        {
                            StudentID = 4,
                            CRAA = 9f,
                            Course = "Ciencia da Computação",
                            Email = "ana_cristina@gmail.com",
                            Name = "ana cristina",
                            Status = "Cursando"
                        },
                        new
                        {
                            StudentID = 5,
                            CRAA = 9f,
                            Course = "Ciencia da Computação",
                            Email = "gabie@gmail.com",
                            Name = "gabie",
                            Status = "Cursando"
                        });
                });

            modelBuilder.Entity("connect_cic_api.Domain.StudentArea", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AreaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("StudentId", "AreaId");

                    b.HasIndex("AreaId");

                    b.ToTable("StudentAreas", (string)null);
                });

            modelBuilder.Entity("connect_cic_api.Domain.StudentDiscipline", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Experience")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Grade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("StudentId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("StudentDisciplines", (string)null);
                });

            modelBuilder.Entity("connect_cic_api.Domain.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProfessorID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rules")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudentID")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserID");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Login = "admin",
                            Password = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
                            Rules = 0
                        },
                        new
                        {
                            UserID = 2,
                            Login = "professor",
                            Password = "17c1532ca6cff8f6a3a8200028af6c2580bf37f39e10cb0966e8a573e3b24a1f",
                            ProfessorID = 1,
                            Rules = 1
                        },
                        new
                        {
                            UserID = 3,
                            Login = "student",
                            Password = "264c8c381bf16c982a4e59b0dd4c6f7808c51a05f64c35db42cc78a2a72875bb",
                            Rules = 2,
                            StudentID = 1
                        });
                });

            modelBuilder.Entity("connect_cic_api.Domain.Vacancy", b =>
                {
                    b.Property<int>("VacancyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessorID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirements")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int>("VacancyTypeID")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("VacancyID");

                    b.HasIndex("ProfessorID");

                    b.HasIndex("VacancyTypeID");

                    b.ToTable("Vacancies", (string)null);

                    b.HasData(
                        new
                        {
                            VacancyID = 1,
                            Description = "Teste de vaga atual",
                            EndDate = new DateTime(2025, 6, 25, 23, 21, 12, 336, DateTimeKind.Local).AddTicks(36),
                            ProfessorID = 1,
                            ProjectTitle = "Projeto teste de vaga",
                            Requirements = "Teste de vaga atual",
                            StartDate = new DateTime(2025, 5, 26, 23, 21, 12, 333, DateTimeKind.Local).AddTicks(4089),
                            Status = "Aberta",
                            VacancyTypeID = 1,
                            Value = 0f
                        },
                        new
                        {
                            VacancyID = 2,
                            Description = "Teste de vaga antiga",
                            EndDate = new DateTime(2025, 5, 16, 23, 21, 12, 336, DateTimeKind.Local).AddTicks(2197),
                            ProfessorID = 1,
                            ProjectTitle = "Projeto teste de vaga",
                            Requirements = "Teste de vaga antiga",
                            StartDate = new DateTime(2025, 4, 6, 23, 21, 12, 336, DateTimeKind.Local).AddTicks(2189),
                            Status = "Fechada",
                            VacancyTypeID = 1,
                            Value = 0f
                        },
                        new
                        {
                            VacancyID = 3,
                            Description = "Desenvolvimento de aplicação web",
                            EndDate = new DateTime(2025, 6, 5, 23, 21, 12, 336, DateTimeKind.Local).AddTicks(2200),
                            ProfessorID = 2,
                            ProjectTitle = "Sistema de gerenciamento de vendas",
                            Requirements = "Conhecimento em Java",
                            StartDate = new DateTime(2025, 5, 26, 23, 21, 12, 336, DateTimeKind.Local).AddTicks(2200),
                            Status = "Aberta",
                            VacancyTypeID = 1,
                            Value = 1000f
                        },
                        new
                        {
                            VacancyID = 4,
                            Description = "Desenvolvimento de aplicação web",
                            EndDate = new DateTime(2025, 7, 5, 23, 21, 12, 336, DateTimeKind.Local).AddTicks(2207),
                            ProfessorID = 3,
                            ProjectTitle = "Sistema de gerenciamento de vendas",
                            Requirements = "Conhecimento em Java",
                            StartDate = new DateTime(2025, 5, 26, 23, 21, 12, 336, DateTimeKind.Local).AddTicks(2202),
                            Status = "Aberta",
                            VacancyTypeID = 1,
                            Value = 1000f
                        },
                        new
                        {
                            VacancyID = 5,
                            Description = "Desenvolvimento de aplicação web",
                            EndDate = new DateTime(2025, 5, 26, 23, 21, 12, 336, DateTimeKind.Local).AddTicks(2209),
                            ProfessorID = 4,
                            ProjectTitle = "Sistema de gerenciamento de vendas",
                            Requirements = "Conhecimento em Java",
                            StartDate = new DateTime(2025, 5, 16, 23, 21, 12, 336, DateTimeKind.Local).AddTicks(2209),
                            Status = "Aberta",
                            VacancyTypeID = 2,
                            Value = 1000f
                        },
                        new
                        {
                            VacancyID = 6,
                            Description = "Desenvolvimento de aplicação web",
                            EndDate = new DateTime(2025, 6, 25, 23, 21, 12, 336, DateTimeKind.Local).AddTicks(2211),
                            ProfessorID = 2,
                            ProjectTitle = "Sistema de gerenciamento de vendas",
                            Requirements = "Conhecimento em Java",
                            StartDate = new DateTime(2025, 5, 16, 23, 21, 12, 336, DateTimeKind.Local).AddTicks(2211),
                            Status = "Aberta",
                            VacancyTypeID = 3,
                            Value = 700f
                        },
                        new
                        {
                            VacancyID = 7,
                            Description = "Desenvolvimento de aplicação web",
                            EndDate = new DateTime(2025, 7, 5, 23, 21, 12, 336, DateTimeKind.Local).AddTicks(2213),
                            ProfessorID = 3,
                            ProjectTitle = "Sistema de gerenciamento de vendas",
                            Requirements = "Conhecimento em Java",
                            StartDate = new DateTime(2025, 5, 26, 23, 21, 12, 336, DateTimeKind.Local).AddTicks(2213),
                            Status = "Aberta",
                            VacancyTypeID = 4,
                            Value = 0f
                        },
                        new
                        {
                            VacancyID = 8,
                            Description = "Desenvolvimento de aplicação web",
                            EndDate = new DateTime(2025, 6, 5, 23, 21, 12, 336, DateTimeKind.Local).AddTicks(2216),
                            ProfessorID = 4,
                            ProjectTitle = "Sistema de gerenciamento de vendas",
                            Requirements = "Conhecimento em Java",
                            StartDate = new DateTime(2025, 5, 26, 23, 21, 12, 336, DateTimeKind.Local).AddTicks(2215),
                            Status = "Aberta",
                            VacancyTypeID = 5,
                            Value = 1000f
                        });
                });

            modelBuilder.Entity("connect_cic_api.Domain.VacancyType", b =>
                {
                    b.Property<int>("VacancyTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("VacancyTypeID");

                    b.ToTable("VacancyTypes", (string)null);

                    b.HasData(
                        new
                        {
                            VacancyTypeID = 1,
                            Name = "Estágio"
                        },
                        new
                        {
                            VacancyTypeID = 2,
                            Name = "Iniciação Cientifica"
                        },
                        new
                        {
                            VacancyTypeID = 3,
                            Name = "Iniciação a docencia"
                        },
                        new
                        {
                            VacancyTypeID = 4,
                            Name = "TCC"
                        },
                        new
                        {
                            VacancyTypeID = 5,
                            Name = "Projeto de Extensão"
                        });
                });

            modelBuilder.Entity("StudentVacancy", b =>
                {
                    b.HasOne("connect_cic_api.Domain.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("connect_cic_api.Domain.Vacancy", null)
                        .WithMany()
                        .HasForeignKey("VacanciesVacancyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("connect_cic_api.Domain.Professor", b =>
                {
                    b.HasOne("connect_cic_api.Domain.User", "User")
                        .WithOne("Professor")
                        .HasForeignKey("connect_cic_api.Domain.Professor", "UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("connect_cic_api.Domain.Student", b =>
                {
                    b.HasOne("connect_cic_api.Domain.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("connect_cic_api.Domain.Student", "UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("connect_cic_api.Domain.StudentArea", b =>
                {
                    b.HasOne("connect_cic_api.Domain.Area", "Area")
                        .WithMany("StudentAreas")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("connect_cic_api.Domain.Student", "Student")
                        .WithMany("StudentAreas")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("connect_cic_api.Domain.StudentDiscipline", b =>
                {
                    b.HasOne("connect_cic_api.Domain.Discipline", "Discipline")
                        .WithMany("StudentDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("connect_cic_api.Domain.Student", "Student")
                        .WithMany("StudentDisciplines")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("connect_cic_api.Domain.Vacancy", b =>
                {
                    b.HasOne("connect_cic_api.Domain.Professor", "Professor")
                        .WithMany("Vacancies")
                        .HasForeignKey("ProfessorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("connect_cic_api.Domain.VacancyType", "VacancyType")
                        .WithMany("Vacancies")
                        .HasForeignKey("VacancyTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("VacancyType");
                });

            modelBuilder.Entity("connect_cic_api.Domain.Area", b =>
                {
                    b.Navigation("StudentAreas");
                });

            modelBuilder.Entity("connect_cic_api.Domain.Discipline", b =>
                {
                    b.Navigation("StudentDisciplines");
                });

            modelBuilder.Entity("connect_cic_api.Domain.Professor", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("connect_cic_api.Domain.Student", b =>
                {
                    b.Navigation("StudentAreas");

                    b.Navigation("StudentDisciplines");
                });

            modelBuilder.Entity("connect_cic_api.Domain.User", b =>
                {
                    b.Navigation("Professor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("connect_cic_api.Domain.VacancyType", b =>
                {
                    b.Navigation("Vacancies");
                });
#pragma warning restore 612, 618
        }
    }
}
